export interface Car {
  id: number
  brand: string
  model: string
  price: number
  year: number
  fuel: string
  km: number
  image: string
  rating: number
  reviews: number
}

export const cars: Car[] = [
  {
    id: 1,
    brand: "Renault",
    model: "Clio",
    price: 8900,
    year: 2022,
    fuel: "Petrol",
    km: 45000,
    image: "/renault-clio-compact-car.jpg",
    rating: 4.5,
    reviews: 28,
  },
  {
    id: 2,
    brand: "Fiat",
    model: "Panda",
    price: 7500,
    year: 2021,
    fuel: "Petrol",
    km: 52000,
    image: "/fiat-panda-city-car.jpg",
    rating: 4.3,
    reviews: 35,
  },
  {
    id: 3,
    brand: "Peugeot",
    model: "208",
    price: 9200,
    year: 2022,
    fuel: "Diesel",
    km: 38000,
    image: "/peugeot-208-hatchback.jpg",
    rating: 4.6,
    reviews: 42,
  },
  {
    id: 4,
    brand: "Citroën",
    model: "C3",
    price: 8800,
    year: 2021,
    fuel: "Petrol",
    km: 48000,
    image: "/citroen-c3-compact.jpg",
    rating: 4.4,
    reviews: 30,
  },
  {
    id: 5,
    brand: "Dacia",
    model: "Sandero",
    price: 6900,
    year: 2020,
    fuel: "Petrol",
    km: 65000,
    image: "/dacia-sandero-affordable.jpg",
    rating: 4.2,
    reviews: 24,
  },
  {
    id: 6,
    brand: "Volkswagen",
    model: "Polo",
    price: 10500,
    year: 2023,
    fuel: "Petrol",
    km: 15000,
    image: "/volkswagen-polo-quality-car.jpg",
    rating: 4.7,
    reviews: 56,
  },
  {
    id: 7,
    brand: "Toyota",
    model: "Yaris",
    price: 11200,
    year: 2023,
    fuel: "Hybrid",
    km: 12000,
    image: "/toyota-yaris-hybrid.jpg",
    rating: 4.8,
    reviews: 64,
  },
  {
    id: 8,
    brand: "Opel",
    model: "Corsa",
    price: 9800,
    year: 2022,
    fuel: "Petrol",
    km: 42000,
    image: "/opel-corsa-hatchback.jpg",
    rating: 4.5,
    reviews: 38,
  },
  {
    id: 9,
    brand: "Seat",
    model: "Ibiza",
    price: 9700,
    year: 2022,
    fuel: "Petrol",
    km: 44000,
    image: "/seat-ibiza-sporty.jpg",
    rating: 4.4,
    reviews: 33,
  },
  {
    id: 10,
    brand: "Ford",
    model: "Fiesta",
    price: 10000,
    year: 2023,
    fuel: "Petrol",
    km: 18000,
    image: "/ford-fiesta-performance.jpg",
    rating: 4.6,
    reviews: 45,
  },
  {
    id: 11,
    brand: "Nissan",
    model: "Micra",
    price: 8000,
    year: 2021,
    fuel: "Petrol",
    km: 55000,
    image: "/nissan-micra-practical.jpg",
    rating: 4.3,
    reviews: 29,
  },
  {
    id: 12,
    brand: "Hyundai",
    model: "i20",
    price: 9600,
    year: 2022,
    fuel: "Petrol",
    km: 39000,
    image: "/hyundai-i20-modern.jpg",
    rating: 4.5,
    reviews: 36,
  },
  {
    id: 13,
    brand: "Kia",
    model: "Rio",
    price: 10300,
    year: 2023,
    fuel: "Diesel",
    km: 20000,
    image: "/kia-rio-value.jpg",
    rating: 4.6,
    reviews: 48,
  },
  {
    id: 14,
    brand: "Renault",
    model: "Captur",
    price: 13500,
    year: 2023,
    fuel: "Petrol",
    km: 14000,
    image: "/renault-captur-suv-crossover.jpg",
    rating: 4.7,
    reviews: 52,
  },
  {
    id: 15,
    brand: "Audi",
    model: "A3",
    price: 17000,
    year: 2023,
    fuel: "Diesel",
    km: 22000,
    image: "/audi-a3-premium-sedan.jpg",
    rating: 4.8,
    reviews: 71,
  },
  {
    id: 16,
    brand: "Volkswagen",
    model: "Golf",
    price: 15800,
    year: 2023,
    fuel: "Petrol",
    km: 19000,
    image: "/volkswagen-golf-classic.jpg",
    rating: 4.7,
    reviews: 58,
  },
  {
    id: 17,
    brand: "Peugeot",
    model: "308",
    price: 13900,
    year: 2023,
    fuel: "Petrol",
    km: 23000,
    image: "/placeholder.svg?height=250&width=350",
    rating: 4.6,
    reviews: 44,
  },
  {
    id: 18,
    brand: "Fiat",
    model: "Tipo",
    price: 11700,
    year: 2023,
    fuel: "Petrol",
    km: 17000,
    image: "/placeholder.svg?height=250&width=350",
    rating: 4.5,
    reviews: 40,
  },
  {
    id: 19,
    brand: "Skoda",
    model: "Fabia",
    price: 9500,
    year: 2022,
    fuel: "Petrol",
    km: 41000,
    image: "/placeholder.svg?height=250&width=350",
    rating: 4.4,
    reviews: 32,
  },
  {
    id: 20,
    brand: "Toyota",
    model: "Corolla",
    price: 14800,
    year: 2023,
    fuel: "Petrol",
    km: 21000,
    image: "/placeholder.svg?height=250&width=350",
    rating: 4.7,
    reviews: 61,
  },
]
